-- CivicOS S00 permission catalogue.
-- Authorization services consume keys and scopes, never role labels directly.

local CivicOS = rawget(_G, "CivicOS") or {}
_G.CivicOS = CivicOS

local Permissions = {
    Version = 1,

    Scope = {
        OWN = "own",
        ASSIGNED = "assigned",
        DEPARTMENT = "department",
        GLOBAL = "global",
    },

    Keys = {
        REQUEST_CREATE = "request.create",
        REQUEST_READ_OWN = "request.read.own",
        REQUEST_READ_DEPARTMENT = "request.read.department",
        REQUEST_TRIAGE = "request.triage",
        REQUEST_ACCEPT = "request.accept",
        REQUEST_REJECT = "request.reject",
        REQUEST_CONVERT = "request.convert",
        REQUEST_REOPEN = "request.reopen",
        REQUEST_COMMENT_OWN = "request.comment.own",
        REQUEST_COMMENT_INTERNAL = "request.comment.internal",
        REQUEST_TIMELINE_PUBLIC = "request.timeline.public",

        WORKORDER_READ_ASSIGNED = "workorder.read.assigned",
        WORKORDER_READ_DEPARTMENT = "workorder.read.department",
        WORKORDER_CREATE = "workorder.create",
        WORKORDER_ASSIGN = "workorder.assign",
        WORKORDER_SELF_ASSIGN = "workorder.self_assign",
        WORKORDER_UPDATE_ASSIGNED = "workorder.update.assigned",
        WORKORDER_CANCEL = "workorder.cancel",
        WORKORDER_DEPENDENCY_MANAGE = "workorder.dependency.manage",

        FIELD_ACTION_EXECUTE = "field.action.execute",
        FIELD_CHECKLIST_UPDATE = "field.checklist.update",
        FIELD_EVIDENCE_ATTACH = "field.evidence.attach",
        FIELD_INSPECTION_EXECUTE = "field.inspection.execute",

        EMPLOYEE_READ_DEPARTMENT = "employee.read.department",
        EMPLOYEE_MANAGE = "employee.manage",
        EMPLOYEE_CERTIFICATION_MANAGE = "employee.certification.manage",
        DUTY_UPDATE_SELF = "duty.update.self",

        DEPARTMENT_READ = "department.read",
        DEPARTMENT_MANAGE = "department.manage",
        SLA_READ = "sla.read",
        SLA_MANAGE = "sla.manage",
        AUDIT_READ = "audit.read",
        ANALYTICS_READ = "analytics.read",
        SYSTEM_CONFIG_MANAGE = "system.config.manage",
    },

    Roles = {
        CITIZEN = {
            label = "Citizen",
            scope = "own",
            permissions = {
                "request.create",
                "request.read.own",
                "request.comment.own",
                "request.timeline.public",
            },
        },

        TECHNICIAN = {
            label = "Technician",
            scope = "assigned",
            permissions = {
                "request.read.own",
                "request.timeline.public",
                "workorder.read.assigned",
                "workorder.self_assign",
                "workorder.update.assigned",
                "field.action.execute",
                "field.checklist.update",
                "field.evidence.attach",
                "duty.update.self",
            },
        },

        DISPATCHER = {
            label = "Dispatcher",
            scope = "department",
            permissions = {
                "request.read.department",
                "request.triage",
                "request.accept",
                "request.reject",
                "request.convert",
                "request.comment.internal",
                "workorder.read.department",
                "workorder.create",
                "workorder.assign",
                "workorder.update.assigned",
                "workorder.dependency.manage",
                "employee.read.department",
                "department.read",
                "sla.read",
            },
        },

        SUPERVISOR = {
            label = "Supervisor",
            scope = "department",
            permissions = {
                "request.read.department",
                "request.triage",
                "request.accept",
                "request.reject",
                "request.convert",
                "request.reopen",
                "request.comment.internal",
                "workorder.read.department",
                "workorder.create",
                "workorder.assign",
                "workorder.cancel",
                "workorder.update.assigned",
                "workorder.dependency.manage",
                "field.inspection.execute",
                "employee.read.department",
                "department.read",
                "sla.read",
                "sla.manage",
                "audit.read",
                "analytics.read",
            },
        },

        DEPARTMENT_ADMIN = {
            label = "Department Admin",
            scope = "department",
            permissions = {
                "request.read.department",
                "request.triage",
                "request.accept",
                "request.reject",
                "request.convert",
                "request.reopen",
                "request.comment.internal",
                "workorder.read.department",
                "workorder.create",
                "workorder.assign",
                "workorder.cancel",
                "workorder.update.assigned",
                "workorder.dependency.manage",
                "field.inspection.execute",
                "employee.read.department",
                "employee.manage",
                "employee.certification.manage",
                "department.read",
                "department.manage",
                "sla.read",
                "sla.manage",
                "audit.read",
                "analytics.read",
            },
        },

        SYSTEM_ADMIN = {
            label = "System Admin",
            scope = "global",
            permissions = {
                "request.create",
                "request.read.own",
                "request.read.department",
                "request.triage",
                "request.accept",
                "request.reject",
                "request.convert",
                "request.reopen",
                "request.comment.own",
                "request.comment.internal",
                "request.timeline.public",
                "workorder.read.assigned",
                "workorder.read.department",
                "workorder.create",
                "workorder.assign",
                "workorder.self_assign",
                "workorder.update.assigned",
                "workorder.cancel",
                "workorder.dependency.manage",
                "field.action.execute",
                "field.checklist.update",
                "field.evidence.attach",
                "field.inspection.execute",
                "employee.read.department",
                "employee.manage",
                "employee.certification.manage",
                "duty.update.self",
                "department.read",
                "department.manage",
                "sla.read",
                "sla.manage",
                "audit.read",
                "analytics.read",
                "system.config.manage",
            },
        },
    },

    RoleMapping = {
        citizen = "CITIZEN",
        technician = "TECHNICIAN",
        dispatcher = "DISPATCHER",
        supervisor = "SUPERVISOR",
        department_admin = "DEPARTMENT_ADMIN",
        system_admin = "SYSTEM_ADMIN",
    },

    JobRoleMapping = {
        dispatcher = "DISPATCHER",
        dispatch = "DISPATCHER",
        supervisor = "SUPERVISOR",
        manager = "SUPERVISOR",
        department_admin = "DEPARTMENT_ADMIN",
        admin = "DEPARTMENT_ADMIN",
        system_admin = "SYSTEM_ADMIN",
    },
}

CivicOS.Permissions = Permissions
return Permissions
